=== gabikiwi/jaxb/XSDTransformJava/schemas/purchase.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://kiwi.org/PurchaseOrderSchema.xsd" targetNamespace="http://kiwi.org/PurchaseOrderSchema.xsd"
	elementFormDefault="qualified">


	<xsd:element name='purchaseOrder' type='tns:PurchaseOrderType' />
	<xsd:element name='comment' type='xsd:string' />
	
	
	<xsd:complexType name='AddressType'>
		<xsd:sequence>
			<xsd:element name='name' type='xsd:string' />
			<xsd:element name='street' type='xsd:string' />
			<xsd:element name='city' type='xsd:string' />
			<xsd:element name='state' type='xsd:string' />
			<xsd:element name='zip' type='xsd:decimal' />
		</xsd:sequence>
		<xsd:attribute name='country' type='xsd:NMTOKEN'/>
	</xsd:complexType>

	<xsd:simpleType name='SKU'>
		<xsd:restriction base='xsd:string'>
			<xsd:pattern value='\d{3}\w{3}' />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name='Items'>
		<xsd:sequence>
			<xsd:element name='item' minOccurs='0' maxOccurs='unbounded'>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name='productName' type='xsd:string' />
						<xsd:element name='quantity'>
							<xsd:simpleType>
								<xsd:restriction base='xsd:positiveInteger'>
									<xsd:minInclusive value='1' />
									<xsd:maxExclusive value='100' />
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:element>
						<xsd:element name='Price' type='xsd:decimal' />
						<xsd:element ref='tns:comment' />
						<xsd:element name='shipDate' type='xsd:date'
							minOccurs='0' />
					</xsd:sequence>
					<xsd:attribute name='partNum' type='tns:SKU' />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name='PurchaseOrderType'>
		<xsd:sequence>
			<xsd:element name='shipTo' type='tns:AddressType' />
			<xsd:element name='billTo' type='tns:AddressType' />
			<xsd:element ref='tns:comment' minOccurs='0' />
			<xsd:element name='items' type='tns:Items' />
		</xsd:sequence>
		<xsd:attribute name='orderDate' type='xsd:date' />
		<xsd:attribute name='confirmDate' type='xsd:date' use='required' />
	</xsd:complexType>
</xsd:schema>

=== gabikiwi/jaxb/XSDTransformJava/xmlSamples/inputPO.xml
<?xml version="1.0" encoding="utf-8"?>
<purchaseOrder  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://kiwi.org/PurchaseOrderSchema.xsd purchase.xsd"
               xmlns="http://kiwi.org/PurchaseOrderSchema.xsd"
orderDate="2012-12-13" confirmDate="2012-12-13">
  <shipTo country="DE">
    <name>Max Mustermann</name>
    <street>Lindenstrasse</street>
    <city>Berlin</city>
    <state>Berlin</state>
    <zip>1234</zip>
  </shipTo>
  <billTo country="DE">
    <name>Fielmann</name>
    <street>Adenauer</street>
    <city>Berlin</city>
    <state>Berlin</state>
    <zip>45678</zip>
  </billTo>
  <comment>DHL</comment>
  <items>
    <item partNum="134str">
      <productName>str1234</productName>
      <quantity>90</quantity>
      <Price>123.45</Price>
      <comment>str1234</comment>
      <shipDate>2015-12-13</shipDate>
    </item>
  </items>
</purchaseOrder>
